(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> 'DAL' object has no attribute 'people'"
p3
sS'layer'
p4
S'/Users/nihil/PycharmProjects/untitled/web2py/applications/ang2py/controllers/plugin_angular.py'
p5
sS'code'
p6
S"__author__ = 'nihil'\n\nfrom plugin_angular import jsoned\n\n@auth.requires_login()\n@jsoned\ndef model():\n    from operator import isSequenceType\n    jsvalidators = {\n        IS_IN_DB : lambda x : '',\n        IS_LENGTH : lambda x : 'is_length(%d,%d)' % (x.minsize,x.maxsize),\n    }\n    model = db[request.args[0] if request.args else request.vars.model]\n    return dict((field.name,dict(\n        name = field.label,\n        validators = filter(bool,map(jsvalidators.get,field.requires if isSequenceType(field.requires) else [field.requires])),\n        comment = field.comment,\n        readable = field.readable,\n        writable = field.writable,\n        type = field.type,\n        w2pwidget = field.widget,\n    )) for field in (\n        getattr(model,field)\n        for field in model.fields\n    ))\n\nresponse._vars=response._caller(model)\n"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/Users/nihil/PycharmProjects/untitled/web2py/gluon/restricted.py", line 224, in restricted\n    exec ccode in environment\n  File "/Users/nihil/PycharmProjects/untitled/web2py/applications/ang2py/controllers/plugin_angular.py", line 27, in <module>\n  File "/Users/nihil/PycharmProjects/untitled/web2py/gluon/globals.py", line 393, in <lambda>\n    self._caller = lambda f: f()\n  File "/Users/nihil/PycharmProjects/untitled/web2py/gluon/tools.py", line 3444, in f\n    return action(*a, **b)\n  File "applications/ang2py/modules/plugin_angular.py", line 30, in x\n    raise e\nAttributeError: \'DAL\' object has no attribute \'people\'\n'
p11
s.